title: Husang Kim
description: "PhD candidate in Economics at the University of Texas at Austin. Research interests: Business Cycles, Asset Pricing, Expectation Formation."
url: "https://husang-kim.github.io"
baseurl: ""

# Build settings
markdown: kramdown
